name: Auto-Convert Manual to BMP

on:
  push:
    branches: ["*"]
    paths:
      - '/manual/resources'

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Convert Manual Images to BMP"
    outputs:
      commit_tag: ${{ steps.make-cias.outputs.commit_tag }}
      commit_message: ${{ steps.make-cias.outputs.commit_message }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: "Install Firefox"
        run: |
          sudo apt-get update
          sudo apt-get install firefox imagemagick -y
      - name: "Take PNG images"
        run: |
          mkdir ~/renders/
          mkdir ~/toUpload/

          mkdir ~/renders/english
          mkdir ~/toUpload/english
          for page in manual/resources/english/*.html; do
            firefox --screenshot ~/renders/english/$(basename $page).png --window-size 256 file://$(pwd)/$page
            magick convert ~/renders/english/$(basename $page).png -define bmp:subtype=RGB565 ~/toUpload/english/$(basename $page).bmp
          done
      - name: "Publish build to GH Actions"
        uses: actions/upload-artifact@v2
        with:
          path: ~/toupload/
          name: "build"